### ISSUE TITLE
Example setting tab not displaying

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give-Settings-API-Example#1]
I just installed and activated this plugin and am not seeing a new tab added to my settings screen even though I'm on `release/1.8`

**Comment by ravinderk** [comment]
@DevinWalker This is fixed. You can review it.

<img width="752" alt="screen shot 2016-10-28 at 10 26 07 am" src="https://cloud.githubusercontent.com/assets/1784821/19795441/00f81d52-9cf9-11e6-8a8a-a27b14b70a0d.png">
<img width="1059" alt="screen shot 2016-10-28 at 10 26 15 am" src="https://cloud.githubusercontent.com/assets/1784821/19795442/010a2e52-9cf9-11e6-9849-092642a1dcac.png">

**Comment by DevinWalker** [comment]
Great, it works. Thanks!
